no9="
SELECT count(1) FROM USER_OBJECTS WHERE OBJECT_NAME IN (
SELECT API_NAME FROM CB_API_MASTER)
AND STATUS <> 'VALID';
"

no10="
SELECT COUNT(1) FROM CB_UPLOAD_STATUS 
WHERE (UPLOAD_DATE_D BETWEEN TRUNC(SYSDATE) -1 
AND TRUNC(SYSDATE) AND STATUS_V IN ('Q','U'))
and upload_key_v not in ('STRPCK','SIMUPLD','IPUPLD');
"

no12="
SELECT COUNT(1) FROM CB_UPLOAD_LOG  WHERE PROCESSED_DATE_DT >= TRUNC(SYSDATE);
"

no16="
SELECT COUNT (1)
FROM CB_SUBS_POS_SERVICES
WHERE TRANS_DATE_DT BETWEEN TRUNC (SYSDATE) - 1 AND TRUNC (SYSDATE)
AND STATUS_OPTN_V = 'R';
"

no25="
SELECT COUNT(1) FROM CB_CS_DEDICATED_ACCOUNT_MAST   WHERE UPLOADED_DATE_DT >= TRUNC(SYSDATE)-1;
"

no26="
SELECT COUNT(1) FROM CB_CS_OFFER WHERE UPLOADED_DATE_dT >= TRUNC(SYSDATE)-1;
"
