@@commands_csv.sql

prompt Count, Description

SELECT COUNT(1), A.DESCRIPTION 
FROM PS_aCTION A, CB_SUBS_PROVISIONING B 
WHERE STATUS_V ='R' AND TRUNC(ACTION_DATE_DT) BETWEEN TRUNC(SYSDATE)-1 AND TRUNC(SYSDATE)
AND A.ACTION_CODE=B.ACTION_CODE_V
AND nvl(scheme_Ref_code_n,0) not in (2004,2005,2006)
AND b.user_code_n not in (642, 583, 497)
GROUP BY A.DESCRIPTION;

EXIT;
