@@commands_csv.sql

prompt Account Link Code Count

SELECT COUNT(DISTINCT (SERV_ACC_LINK_CODE_N)) 
FROM CB_OFFERS A, CB_INVOICE_DETAILS B 
WHERE BILL_CYCLE_FULL_CODE_N = &1
AND A.SCHEME_REF_CODE_N=B.SCHEME_REF_CODE_N 
AND TRANS_AMT_N > 0 
AND DB_CR_V='C' 
AND (B.SCHEME_REF_CODE_N,ARTICLE_CODE_V) IN
(SELECT SCHEME_REF_CODE_N,ARTICLE_CODE_V FROM CB_SUBSCRIPTION_ARTICLES  WHERE SCHEME_REF_CODE_N IN (
SELECT SCHEME_REF_CODE_N FROM CB_OFFERS WHERE (OFFER_DESC_V LIKE '%DATA%' OR OFFER_DESC_V LIKE '%BB%') AND CONTRACT_TYPE_N ='N'));

EXIT;
