@@commands.sql

prompt Mobile Number, SIM Number, Error Description

SELECT DISTINCT MOBILE_NUMBER_V, SIM_NUM_V, ERROR_DESCRIPTION_V 
FROM GSM_SIM_REGISTRATION_DETAILS
WHERE REGISTRATION_DATE_DT BETWEEN TRUNC(SYSDATE) -1 AND TRUNC(SYSDATE)
AND ERROR_DESCRIPTION_V NOT IN ('MSISDN ALREADY REGISTERED')
AND ACTIVITY_TYPE_V = 'SIM'
AND STATUS_V ='F';

exit;
