-- 13.
SELECT DISTINCT MOBL_NUM_V 
FROM CB_UPLOAD_REJECTED_CDRS 
WHERE CALL_DATE_DT BETWEEN TRUNC(SYSDATE)-1 AND TRUNC(SYSDATE)  
AND CORRECTED_STATUS_V <>'G';

-- 14.
SELECT remark_v,count(1) 
FROM CB_TT_MNP_INT_API_LOG 
WHERE ACTION_DATE_DT 
BETWEEN TRUNC(SYSDATE)-1 AND TRUNC(SYSDATe)
AND STATUS_V NOT IN('Q','T','S','I','R','N','O','E','P','B')
AND REMARK_v NOT LIKE ('%completed porting within the last 30 days') 
AND REMARK_V NOT LIKE ('%is already subject to a porting process%')
AND REMARK_V NOT LIKE '%P-XSThe recipient (MTNGMN) needs to differ from the donor (MTNGMN)%'
AND REMARK_V NOT LIKE 'PORT OUT Authentication Failed,User Must be in the Network for atleast 30 Days'
group by remark_v;

-- 15.
SELECT COUNT(1), A.DESCRIPTION 
FROM PS_ACTION A, CB_SUBS_PROVISIONING B
WHERE STATUS_V ='R' AND SYS_EXTRACT_UTC("ACTION_DATE_DT")
BETWEEN TRUNC(SYSDATE)-1 AND TRUNC(SYSDATE)
AND A.ACTION_CODE=B.ACTION_CODE_V
AND scheme_ref_code_n NOT IN (2004,2005,2003)
AND CAI_CMD_REQ_STRING NOT LIKE 'DELETE:SUBSCRIBER:2:SubscriberNumber%'
GROUP BY ACTION_CODE_V, A.DESCRIPTION;

-- 23.
SELECT SERVICE_ID_V 
FROM CB_SUBS_PROVISIONING 
WHERE STATUS_V='R' 
AND ACCOUNT_LINK_CODE_N IN (
SELECT SERV_ACC_LINK_CODE_N 
FROM CB_SCHEDULES 
WHERE PROCESS_ON_DATE_D >= TRUNC(SYSDATE)-3 
AND SERVICE_KEY_CODE_v ='PPRT')
AND ACTION_CODE_V ='ERAS';