@@commands.sql

SELECT MOBL_NUM_VOICE_V||','||'PAM2'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST WHERE MOBL_NUM_VOICE_V IN (
SELECT MOBILE_NUMBER_V 
FROM CB_TT_MNP_INT_API_LOG 
WHERE TRUNC(EXECUTION_DATE_DT) >= TRUNC(SYSDATE) -5 AND STATUS_V ='I')
AND CONTRACT_TYPE_V ='P'
AND ACCOUNT_LINK_CODE_N NOT IN (
SELECT ACCOUNT_LINK_CODE_N 
FROM CB_SUBS_OFFER_dETAILS 
WHERE OFFER_CODE_v='PAM2') 
union
SELECT MOBL_NUM_VOICE_V||','||'PROMO'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST WHERE MOBL_NUM_VOICE_V IN (
SELECT MOBILE_NUMBER_V 
FROM CB_TT_MNP_INT_API_LOG 
WHERE TRUNC(EXECUTION_DATE_DT) >= TRUNC(SYSDATE) -5 AND STATUS_V ='I')
AND CONTRACT_TYPE_V ='P'
AND ACCOUNT_LINK_CODE_N NOT IN (
SELECT ACCOUNT_LINK_CODE_N 
FROM CB_SUBS_OFFER_dETAILS 
WHERE OFFER_CODE_v='PROMO') 
union
SELECT MOBL_NUM_VOICE_V||','||'SOFF10'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST WHERE MOBL_NUM_VOICE_V IN (
SELECT MOBILE_NUMBER_V 
FROM CB_TT_MNP_INT_API_LOG 
WHERE TRUNC(EXECUTION_DATE_DT) >= TRUNC(SYSDATE) -5 AND STATUS_V ='I')
AND CONTRACT_TYPE_V ='P'
AND ACCOUNT_LINK_CODE_N NOT IN (
SELECT ACCOUNT_LINK_CODE_N 
FROM CB_SUBS_OFFER_dETAILS 
WHERE OFFER_CODE_v='SOFF10');

EXIT;
