@@commands.sql

SELECT MOBL_NUM_VOICE_V||','||'EOCN73'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST WHERE MOBL_NUM_VOICE_V IN (
SELECT MOBILE_NUMBER_V 
FROM CB_TT_MNP_INT_API_LOG 
WHERE TRUNC(EXECUTION_DATE_DT) >= TRUNC(SYSDATE) -3 AND STATUS_V ='I')
AND CONTRACT_TYPE_V ='P'
AND ACCOUNT_LINK_CODE_N NOT IN (
SELECT ACCOUNT_LINK_CODE_N 
FROM CB_SUBS_OFFER_dETAILS 
WHERE OFFER_CODE_v='EOCN73') UNION
SELECT MOBL_NUM_VOICE_V||','||'EOCN73'||','||'ADD VAS'||','||',' 
FROM gsm_service_mast a
WHERE mobl_num_voice_V IN
(SELECT mobile_number_v 
FROM GSM_SIM_REGISTRATION_DETAILS 
WHERE REGISTRATION_DATE_DT>=TRUNC(SYSDATE)-3
AND activity_type_v='SIM'
AND registration_done_by_n 
NOT IN (3482,3481) 
AND status_v='S')
AND NOT EXISTS (SELECT 1 FROM cb_subs_offer_details b 
WHERE a.account_link_code_n=b.account_link_code_n
AND offer_code_v='EOCN73');

EXIT;
