@@commands.sql

SELECT MOBL_NUM_VOICE_V||','||'VEHT MO'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST 
WHERE STATUS_CODE_V='AC' 
AND CONTRACT_TYPE_V='N' 
AND ACTIVATION_DATE_D >= TRUNC(SYSDATE)
AND  TARIFF_CODE_V='VEHT'
UNION ALL
SELECT MOBL_NUM_VOICE_V||','||'VHT_PRO'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST 
WHERE STATUS_CODE_V='AC' 
AND CONTRACT_TYPE_V='N' 
AND ACTIVATION_DATE_D >= TRUNC(SYSDATE)
AND TARIFF_CODE_V='VEHT'
UNION ALL
SELECT MOBL_NUM_VOICE_V||','||'VEHT MT'||','||'ADD VAS'||','||',' 
FROM GSM_sERVICE_MAST 
WHERE STATUS_CODE_V='AC' 
AND CONTRACT_TYPE_V='N' 
AND ACTIVATION_DATE_D >= TRUNC(SYSDATE)
AND  TARIFF_CODE_V='VEHT';

EXIT;
